<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DependencyProviderV2</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Blaze.Interaction.Provider.Abstractions\Blaze.Interaction.Provider.Abstractions.csproj" />
    <ProjectReference Include="..\DependencyV2\DependencyV2.csproj" />
  </ItemGroup>
</Project>
